# Generated by Django 5.0.3 on 2024-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='editado',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='editado',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='editado',
        ),
        migrations.AddField(
            model_name='cargo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='criado',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='criado',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='criado',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
